import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Container, Flex, Text, HStack } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  return (
    <>
      <Head>
        <title>E2E runner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100vw" alignContent="center" >
          <Text fontSize="1vw" color="#1F79BA" lineHeight="40px" flexGrow={1}>AT&T E2E Runner</Text>
          <HStack spacing="1vw">
            <Text>Test Editor</Text>
            <Text>Results</Text>
            <Text >Scheduler</Text>
          </HStack>
      </Flex>
    </>
  )
}
